# Main configuration file
project_name: ml-project
version: 0.1.0

# Data configuration
data:
  raw_path: data/raw
  processed_path: data/processed
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

# Model configuration
model:
  name: "default_model"
  seed: 42

# Training configuration
training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  optimizer: adam

# Logging configuration
logging:
  level: INFO
  log_dir: logs
  
# Experiment tracking
experiment:
  name: "default_experiment"
  tags: []
  
# Paths
paths:
  models: models/
  reports: reports/
  logs: logs/
